# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- release*
- Release*
- Dev*
- dev*

resources:
  repositories:
  - repository: devops-tools
    type: git
    name: ProductionTestSWPlatform/PTD_DevOps_Tools
    endpoint: PTD_Azure_DevOps_Connection

jobs:
- template: azure-devops/template-pipeline-test.yaml@devops-tools